apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    # Grant admin role to all members of the AD group 'AD-Admins'
    g, DCOps_Admin, role:admin
    g, rajesh.natarajan@e2open.com, role:admin
    # Define the admin role with full access
    p, role:admin, applications, *, */*, allow
    p, role:admin, projects, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, accounts, *, *, allow
    p, role:admin, certificates, *, *, allow
    p, role:admin, gpgkeys, *, *, allow
    p, role:admin, logs, *, *, allow
    p, role:admin, exec, *, *, allow
    p, role:admin, extensions, *, *, allow

  policy.default: role:readonly
  scopes: '[groups]'
  policy.matchMode: glob

