apiVersion: v1
data:
  dex.config: |
    connectors:
    - type: ldap
      id: ldap
      name: LDAP
      config:
        host: "192.168.0.25:389"
        insecureNoSSL: true
        insecureSkipVerify: true
        bindDN: "$dex.ldap.bindDN"
        bindPW: "$dex.ldap.bindPW"
        usernamePrompt: Username
        userSearch:
          baseDN: "dc=homelab,dc=com"
          filter: ""
          username: "sAMAccountName"
          idAttr: "sAMAccountName"
          emailAttr: "mail"
          nameAttr: "cn"
        groupSearch:
          baseDN: "dc=homelab,dc=com"
          filter: "(objectClass=groupOfNames)"
          userMatchers:
            - userAttr: "sAMAccountName"
              groupAttr: "memberUid"
            - userAttr: "DN"
              groupAttr: "member"
          nameAttr: "cn"
  url: https://argocd.homelab.com
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: argocd-task
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd

