apiVersion: v1
data:
  .dockerconfigjson: ==
kind: Secret
metadata:
  annotations:
     argocd.argoproj.io/sync-wave: "1"
  name: regcred
  namespace: vmware-system-tmc
type: kubernetes.io/dockerconfigjson
