apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: blr-dev-poc
  namespace: blr-dev-cops-vns
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.96.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: tanzukubernetescluster
    version: v1.25.7+vmware.3-fips.1-tkg.1
    controlPlane:
      replicas: 1
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
    workers:
      machineDeployments:
        - class: node-pool
          name: node-pool-1
          replicas: 1
          metadata:
            annotations:
              run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu          
    variables:
      - name: ntp
        value: ntp1.homelab.com
      - name: vmClass
        value: best-effort-medium
      - name: storageClass
        value: vmfs-san
      - name: defaultStorageClass
        value: vmfs-san
      - name: clusterEncryptionConfigYaml
        value: |
          apiVersion: apiserver.config.k8s.io/v1
          kind: EncryptionConfiguration
          resources:
            - resources:
                - secrets
              providers:
                - aescbc:
                    keys:
                      - name: key1
                        secret: QiMgJGYXudtljldVyl+AnXQQlk7r9iUXBfVKqdEfKm8=
                - identity: {}
# ADDITIONAL VALUES
      - name: nodePoolVolumes
        value:
        - capacity:
            storage: "100Gi"
          mountPath: "/var/lib/containerd"
          name: containerd
          storageClass: vmfs-san
        - capacity:
            storage: "15Gi"
          mountPath: "/var/lib/kubelet"
          name: kubelet
          storageClass: vmfs-san
      - name: controlPlaneVolumes
        value:
        - capacity:
            storage: "15Gi"
          mountPath: "/var/lib/containerd"
          name: containerd
          storageClass: vmfs-san
        - capacity:
            storage: "15Gi"
          mountPath: "/var/lib/kubelet"
          name: kubelet
          storageClass: vmfs-san
