apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: velero-deployment-kustomize
  namespace: tanzu-continuousdelivery-resources
spec:
  force: false
  interval: 5m0s
  path: ./backup-scheduler-kustomize
  prune: false
  sourceRef:
    kind: GitRepository
    name: infra-gitrepo
    namespace: tanzu-continuousdelivery-resources

