---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    packaging.carvel.dev/package: cert-manager-tanzu-fluxcd-packageinstalls
    tkg.tanzu.vmware.com/tanzu-package: cert-manager-tanzu-fluxcd-packageinstalls
  creationTimestamp: null
  name: cert-manager-tanzu-fluxcd-packageinstalls-sa
  namespace: tanzu-fluxcd-packageinstalls
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    packaging.carvel.dev/package: cert-manager-tanzu-fluxcd-packageinstalls
    tkg.tanzu.vmware.com/tanzu-package: cert-manager-tanzu-fluxcd-packageinstalls
  creationTimestamp: null
  name: cert-manager-tanzu-fluxcd-packageinstalls-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    packaging.carvel.dev/package: cert-manager-tanzu-fluxcd-packageinstalls
    tkg.tanzu.vmware.com/tanzu-package: cert-manager-tanzu-fluxcd-packageinstalls
  creationTimestamp: null
  name: cert-manager-tanzu-fluxcd-packageinstalls-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-tanzu-fluxcd-packageinstalls-cluster-role
subjects:
- kind: ServiceAccount
  name: cert-manager-tanzu-fluxcd-packageinstalls-sa
  namespace: tanzu-fluxcd-packageinstalls
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    packaging.carvel.dev/package-ClusterRole: cert-manager-tanzu-fluxcd-packageinstalls-cluster-role
    packaging.carvel.dev/package-ClusterRoleBinding: cert-manager-tanzu-fluxcd-packageinstalls-cluster-rolebinding
    packaging.carvel.dev/package-ServiceAccount: cert-manager-tanzu-fluxcd-packageinstalls-sa
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: cert-manager-tanzu-fluxcd-packageinstalls-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: cert-manager-tanzu-fluxcd-packageinstalls-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: cert-manager-tanzu-fluxcd-packageinstalls-sa
  creationTimestamp: null
  name: cert-manager
  namespace: tanzu-fluxcd-packageinstalls
spec:
  packageRef:
    refName: cert-manager.tanzu.vmware.com
    versionSelection:
      constraints: 1.12.2+vmware.2-tkg.2
      prereleases: {}
  serviceAccountName: cert-manager-tanzu-fluxcd-packageinstalls-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
